# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: docker build --pull --target testrunner -t dotnetapp:test -f samples/dotnetapp/Dockerfile.alpine-x64 samples/dotnetapp
- script: mkdir TestResults
- script: docker run --rm -v "$(pwd)"/TestResults:/app/tests/TestResults dotnetapp:test
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'