name: aspnetapp-windowsservercore

on:
  push:
    branches:
      - 'main'

jobs:
  docker-windowsservercore:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build --file=Dockerfile.windowsservercore-x64 -t richlander/aspnetapp:windowsservercore ./samples/aspnetapp
          docker push richlander/aspnetapp:windowsservercore
